# Site settings
title: Joris de Wit 
email: joris.w.dewit@gmail.com
description: "The personal site of Joris de Wit. A web developer living in Vancouver BC."
baseurl: ""
url: "http://jorisdewit.ca"
twitter_username: joris_dewit
github_username:  jdewit

# Build settings
markdown: kramdown
permalink: pretty
